name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  create-deployment-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: imranismail/setup-kustomize@v1
      - run: |
          git checkout origin deploy
          kustomize edit set image app:${GITHUB_SHA}
          git add .
          git commit -m "Set `app` image tag to `${GITHUB_SHA}`"
          git push
